spring:
  datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1521:XE
    username: SYSTEM
    password: 1234qwer!@#
    driver-class-name: oracle.jdbc.driver.OracleDriver

  devtools:
    livereload:
      enabled: true

  mvc:
    view:
      prefix: /jsp/
      suffix: .jsp
---
mybatis:
  type-aliases-package: com.example.demo.model
  mapper-locations: classpath:mapper/**/*.xml
---  
server:
  port: 8080
  #httpport: 80

  tomcat:
    uri-encoding: UTF-8
  servlet:
    session:
      timeout: 3600s
      cookie:
        name: JSESSIONIDTABLE

    encoding:
      charset: UTF-8
      enabled: true
      force: true

